### ISSUE TITLE
Error immediately upon launching Rails server after installing gem

### ISSUE THREAD

**Issue by djpowers** [afrase/zerobounce#10]
Hello, I just installed the gem (v0.1.0) to a Rails 4.0.13 project running Ruby 2.2.10p489.

Immediately upon starting the server, I see the following errors:
```
/Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require': /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/zerobounce-0.1.0/lib/zerobounce/error.rb:40: syntax error, unexpected '.' (SyntaxError)
        if env[:body]&.start_with?('Missing parameter')
                       ^
/Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/zerobounce-0.1.0/lib/zerobounce/error.rb:52: syntax error, unexpected '.'
        ApiError.new(env) if env[:body]&.start_with?('{"error":"')
                                         ^
/Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/zerobounce-0.1.0/lib/zerobounce/error.rb:78: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `block in require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:214:in `load_dependency'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/dependencies.rb:229:in `require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/zerobounce-0.1.0/lib/zerobounce.rb:3:in `<top (required)>'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
	from /Users/<username>/<application>/config/application.rb:7:in `<top (required)>'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:74:in `require'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:74:in `block in <top (required)>'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
	from /Users/<username>/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

Removing the gem and rebundling works as normally. If I can assist at all with debugging, please let me know.

**Comment by djpowers** [comment]
I did some investigating and it looks like the safe navigation operator (&.) was added in Ruby 2.3, so it makes sense that a lower version would be getting this error.

One easy solution would be to add a minimum required Ruby version to the gemspec. Alternatively, the code could be refactored to not use the newer syntax.

If you have thoughts on either approach, I'd be happy to draft a PR with whichever one you'd prefer.

**Comment by afrase** [comment]
I think the safe navigators could easily be replaced with `#to_s` since `nil.to_s` = `''`.

**Comment by djpowers** [comment]
Thanks! That seemed to do the trick. No longer getting the aforementioned error, and the specs still pass. Opened up a quick PR with the changes.

**Comment by afrase** [comment]
Thanks for fixing that! I’ll get a new version deployed to ruby greens soon.
